spring:
  datasource:
    url: jdbc:mysql://localhost/Sistema-de-viajes?serverTimezone=UTC  # ?createDatabaseIfNotExist=true # esta linea sería para que se cree sola, pero no me anduvo
    username: root
    password: ser.23
    #initialization-mode: always
  jpa:
    show-sql: false #true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
